### ISSUE TITLE
please add a small readmy, what those packages do

### ISSUE THREAD

**Issue by rubo77** [FreifunkBremen/ffhb-packages#3]

**Comment by jplitza** [comment]
I extended the descriptions in the packages' Makefiles. Hope that will do.

**Comment by rubo77** [comment]
Thats better, thanks.

Maybe a Readme would be usefull for others still, especially a description how to use the gluon-speedtest would be nice.

I thoght about completing the Package collection, you started here: https://github.com/freifunk-gluon/gluon/wiki/Package-collection

It would be nice to have a collection with descriptions for each package
