### ISSUE TITLE
Was macht gluon-radv-filterd noch alles?

### ISSUE THREAD

**Issue by rubo77** [FreifunkBremen/ffhb-packages#4]
Im Readme steht nichts davon, dass durch dieses Paket gesonderte informationen per respondd gesendet werden, mit welchem Gateway man per IPv4 und v6 verbunden ist. Anscheinend braucht yanic ja dieses Paket in der Firmware.

Ausserdem ist nicht klar, ob man das Paket **gluon-ebtables-filter-ra-dhcp** jetzt rausnehmen muss oder nicht? Ihr habt es in eurer Firmware ja noch drin. wie habt ihr das gelöst?

**Comment by jplitza** [comment]
All das steht im Upstream-PR: freifunk-gluon/gluon#838
Wir haben das nur in unserem Repo, weil wir das schon vorm Merge testen wollten.

**Comment by rubo77** [comment]
It would be nice to have a simpler explanation, how I can get the display of the used ipv6 gateway in our Freifunk community without having to wait until it is upstream.

I can only guess, that I could use this package?

Could you say, which packages I need and which not? That would be great.

**Comment by jplitza** [comment]
I try to update our package here every time we need it, but I can't make any guarantees. In particular, the current version in this repo is *severely* less functional than the PR version. However, the PR version needs libbatadv, which is only included in master and not in 2017.1.

**Comment by rubo77** [comment]
Ok. Also reicht es für uns in Kiel für den 2017.1.x Branch, dieses Paket hier mit aufzunehmen und schon zeigt der neue Meshviewer das gewählte ipv6 Gateway an?

Oder muss man noch etwas beachten?

**Comment by jplitza** [comment]
Du fokussierst dich immer so auf das Anzeigen. Dieses Paket *wählt* überhaupt erst einen Gateway! Ohne dieses Paket gehen alle Router Advertisements durch an die Clients und es gibt so etwas wie ein "gewähltes IPv6 Gateway" gar nicht.

Und ja, dieses Paket reicht dafür. Ohne Garantie, dass diese Version funktioniert (bei uns tut sie es häufig genug nicht)

**Comment by rubo77** [comment]
Ah okay. Höchst interessant! Klingt, als wenn das Paket dringend alle bräuchten, oder?

Passiert denn etwas schlimmeres, wenn es Mal nicht klappt? Oder ist das Verhalten dann einfach nur wieder wie vorher, ohne dass Paket?
