### ISSUE TITLE
New backport to 2017.1.x for gluon-radv-filterd

### ISSUE THREAD

**Issue by rubo77** [FreifunkBremen/ffhb-packages#8]
@tobleminer created a new backport out of the current gluon master to 2017.1.x:

https://github.com/freifunk-kiel/ffki-packages

**Comment by jplitza** [comment]
So what would be the difference to our version?

**Comment by rubo77** [comment]
Not sure, I guess It contains all new patches in gluon. You have to ask tsys in IRC

**Comment by jplitza** [comment]
Gluon doesn't have any patches for gluon-radv-filterd newer than our version. The last one was mine that we tested here before it was merged into Gluon.

**Comment by rubo77** [comment]
https://github.com/freifunk-kiel/ffki-packages/blob/lede/gluon-radv-filterd/src/Makefile

sieht ziemlich anders aus als

https://github.com/FreifunkBremen/ffhb-packages/blob/v2017.1/gluon-radv-filterd/src/Makefile

ich stecke da aber nicht drin, weis nicht ob das sinnvoll ist, oder so. Wollte euch nur informieren, dass da arbeit gemacht wurde, die vielleicht brauchbar sein könnte.
